name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Клонирование проекта
        uses: actions/checkout@v4

      - name: Установка JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Установка зависимостей
        run: mvn install

      - name: Запуск тестов
        run: mvn clean test

      - name: Генерация Allure отчета
        run: mvn allure:report

      - name: Загрузка Allure отчета как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/