name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Установить зависимостей
        run: mvn install

      - name: Установка Allure CLI
        run: |
          ALLURE_VERSION=2.33.0
          wget "https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.zip"
          unzip "allure-2.33.0.zip" -d /opt/
          ln -s /opt/allure-2.33.0/bin/allure /usr/local/bin/allure

      - name: Проверка установленной версии Allure
        run: allure --version

      - name: Создание директории allure-results
        run: mkdir -p target/allure-results

      - name: Проверка наличия каталога allure-results
        run: ls -la target/allure-results || echo "Файл или директория allure-results не найдены"

      - name: Создание директории allure-report
        run: mkdir -p target/allure-report

      - name: Проверка наличия каталога allure-report
        run: ls -la target/allure-report || echo "Файл или директория allure-report не найдены"

      - name: Запуск тестов с логированием
        run: mvn clean test | tee test-output.log

      - name: Генерация репорта
        run: |
          allure generate --clean target/allure-results -o allure-report
          

