#
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#    steps:
#    - uses: browser-actions/setup-chrome@v1
#      run: chrome --version
#      return: chrome_browser
#    - uses: actions/checkout@v4
#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#        cache: maven
#    - name: Run tests
#      run: mvn clean test



name: Java CI for UI tests

on:
  push

jobs:

  build:

    runs-on: ubuntu-latst

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test
