name: Java CI with Maven on Windows

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: windows-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/


