name: Java CI with Maven

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - run:
          name: Install Google Chrome
          environment:
            ORB_PARAM_CHROME_VERSION: <<parameters.chrome-version>>
            ORB_PARAM_REPLACE_EXISTING: <<parameters.replace-existing>>
            ORB_PARAM_CHANNEL: << parameters.channel >>
            ORB_PARAM_SAVE_CACHE: <<parameters.use_cache>>
          command: <<include(scripts/install-chrome.sh)>>
      - when:
          condition: <<parameters.use_cache>>
          steps:
            - save_cache:
                key: chrome-<<parameters.cache_key>>-<<parameters.chrome-version>>-{{ arch }}
                paths:
                  - /tmp/chrome.tar.gz

      - name: Run tests
        run: mvn clean test
    uses: