name: Java CI with Maven

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Установка браузера Google Chrome
        hosts: all
        tasks:
          - name: Добавить репозиторий Google Chrome
            apt_repository:
              repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
              state: present

          - name: Установить ключи для репозитория
            apt_key:
              url: 'https://dl.google.com/linux/linux_signing_key.pub'
              state: present

          - name: Обновить список пакетов
            apt:
              update_cache: yes

          - name: Установить Google Chrome
            apt:
              name: google-chrome-stable
              state: present

      - name: Run tests
        run: mvn clean test
    uses: