default:
#  image: maven:3.9.8-amazoncorretto-21
  image: maven:3.9.9-eclipse-temurin-21
  #image: maven:markhobson/maven-chrome

stages:
  - test

before_script:
  # - export MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512m"
  - apt-get update -qq && apt-get install -y wget unzip && apt-get clean

# Job to run API tests
api_tests:
  stage: test
  #image: selenium/standalone-chrome:latest
  script:
    - mvn clean test
  only:
    - main
